logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG
    com.whatsapp.clone.application: DEBUG
spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
