services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-clone-web-container
    ports:
      - '8085:8080'
    depends_on:
      - postgres
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 9095:8080

volumes:
  postgres_data: